name: Update readme

on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

jobs:
  readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1


      - name: Generate readme
        env:
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: node build-svg.js

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Ji young Kim
          author_email: kimyamae82@gmail.com
          message: "Auto updating my readme"
          add: "*.svg"
        env:
          GITHUB_TOKEN: ${{ secrets.GHT }}